[package]
name = "stats_bucket_test_client"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = "1.14.0"
solana-sdk = "1.14.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bs58 = "0.4"