[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
stats_bucket = "FA9zMykeKJd2VEc1iw5toV2Ai9Vc2t23e55rFyh9E88f"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
