[package]
name = "stats_bucket"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.12.0"
solana-program = "1.14.0"
serde = { version = "1.0", features = ["derive"] }
num-integer = "0.1.46" 

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true